id: hl7.fhir.uv.smart-web-messaging
canonical: https://hl7.org/fhir/uv/smart-web-messaging
version: 0.1.0
fhirVersion: 4.0.1
license: Apache-2.0
copyrightYear: 2020+
releaseLabel: Build CI
status: active
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"

name: SmartWebMessaging
title: "SMART Web Messaging Implementation Guide: STU1"
description: The SMART Web Messaging Implementation Guide enables
  SMART-launched apps a standard way to communicate with the fixture that
  launched the app.

publisher:
  name: HL7 FHIR Infrastructure
  url: http://hl7.org/Special/committees/fiwg/index.cfm

contact:
  - name: Carl Anderson
    telecom:
      - system: email
        value: mailto:carl.anderson@microsoft.com

history:
  current: https://build.fhir.org/ig/HL7/smart-web-messaging/
  0.1.0:
    fhirversion: 4.0.1
    date: 2020-08-11
    desc: STU 1 Ballot
    path: https://hl7.org/fhir/uv/smart-web-messaging/2020Sep/
    status: ballot
    sequence: STU 1
    current: false

parameters:
  usage-stats-opt-out: true

menu:
  IG Home: index.html
  TOC: toc.html
